[azure_openai]
api_key = 8804263e0e884a73b493a58f22505cc6
endpoint = https://omh-eus-2-test-01.openai.azure.com/
api_version = 2024-02-01

[gpt_models]
model_gpt4o = OMH-EUS2-GPT4O-1

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002546E0EB770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pandas/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002546E264690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pandas/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002546E264910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pandas/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002546E264B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pandas/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002546E264E10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pandas/
ERROR: Could not find a version that satisfies the requirement pandas (from versions: none)

pip install pandas --cert C:\certs\cacert.pem --trusted-host pypi.org --trusted-host files.pythonhosted.org

[global]
cert = C:\certs\cacert.pem
trusted-host = pypi.org
trusted-host = files.pythonhosted.org

C:\Users\hariVetri\AppData\Roaming\pip\pip.ini

PS C:\Users\HariharaM12\PycharmProjects\PythonProject> pip install pandas
Configuration file could not be loaded.
While reading from 'C:\\ProgramData\\pip\\pip.ini' [line  4]: option 'trusted-host' in section 'global' already exists
